### ISSUE TITLE
possible to execute commands incrementally in GHCI ?

### ISSUE THREAD

**Issue by simonmichael** [kallisti-dev/hs-webdriver#109]
Thanks for this great, super useful lib. (Aside: I found it much easier than the equivalent ruby or javascript libs. I did have quite a bit of trouble getting selenium working on osx. brew install selenium-server-standalone worked in the end, though it doesn't understand some things like getLogs. selenium-server-standalone245 opened the browser only. Other hurdles: getting a new enough java; finding the selenium browser window, which is backgrounded on OSX; discovering the wait* commands in the API and learning when they are needed, eg between openPage and findElem; "element detached from DOM" errors when trying to combine findElems.)

On to my question: it would be really helpful to be able to run exploratory commands one at a time in GHCI and observe the effects, keeping the session open. Is this possible ? I thought I had found a way:
```ghci
*Main> :t runSession defaultConfig $ createSession def
runSession defaultConfig $ createSession def
  :: IO Test.WebDriver.Session.WDSession
```
..but this happens:
```ghci
*Main> s <- runSession defaultConfig $ createSession def
*** Exception: ServerError "Server response session ID (Just (SessionId \"6fabed28-712d-4b48-bb45-88b5f5bf3b5f\")) does not match local session ID (Just (SessionId \"2dc93519-bcab-4588-9bce-18e4dfc82b1f\"))"
```

**Comment by kallisti-dev** [comment]
The problem is that you're creating two different sessions in your example. `runSession` is a convenience method that automatically calls `createSession` for you. So the additional call of `createSession` in your code is overriding the existing session already stored in the state monad.  What you want is:

```haskell
:m Test.WebDriver Test.WebDriver.Session
s <- runSession defaultConfig $ getSession
```

`getSession` from `Test.WebDriver.Session` simply returns the existing session stored in the state monad. Once you have a session, you can then run commands on it like this:

```haskell
runWD s $ openPage "http://example.com"
```

`runSession` creates a new WDSession using the given WDConfig, whereas `runWD` takes an existing WDSession reference and runs commands with that. Perhaps I could organize this more clearly or improve the docs somehow. Any suggestions would be welcome.

**Comment by simonmichael** [comment]
Thanks!
