### ISSUE TITLE
waitForPageLoad

### ISSUE THREAD

**Issue by mf59816** [kallisti-dev/hs-webdriver#72]
Hi,

I just implemented code for making sure a new page has been loaded before returning from a `wd` action.  See here:

https://github.com/liqd/thentos/pull/114

Would you accept a PR that provides `waitForPageLoad` from `Test.WebDriver.Commands.Wait`?  (I would make `ackStaleException` local, but do not insist either way; the `*Sync` seem like too much clutter for a general-purpose webdriver library and I would leave them out.)

Any suggestions welcome.

**Comment by kallisti-dev** [comment]
I have some reservations about this change, mostly because, based on my conversations with the Selenium devs, "page load" is not always an easily well-defined state and so a function named waitForPageLoad might be misleading. So it is often better to explicitly tailor the wait logic to the page at hand, by using explicit waits. 

I think the solution here is, rather than providing a specific function to wait for a stale html element, creating a more general purpose explicit wait function. For a long time I've been considering how to add a function to wait while/until a user-specified exception type occurs, but the primary hurtle has been settling on an easy yet comprehensive way to select specifically what exceptions you want to branch on.

**Comment by fisx** [comment]
That sounds reasonable.  [I'm still mf59816, sorry about the confusion.]

To clarify: do you disagree with http://www.obeythetestinggoat.com/how-to-get-selenium-to-wait-for-page-load-after-a-click.html, or do you think I got the implementation wrong?

(Now that I look at my code again, I recall that there were still some issues with the naive implementation of the blog, and we needed to horrify it by adding some arbitrary threadDelays.  So, good call that you don't want this in the lib.  :-)

Thanks -

**Comment by kallisti-dev** [comment]
All of the points in that post are valid, and the implementation looks mostly correct for what it's intended to do, which is to detect a page load in a very common situation. In fact the points in that post are the reasons why I don't want to include a function named waitForPageLoad. It shouldn't be called waitForPageLoad because the name misleads people into thinking that it will always properly detect page loads on all possible web pages.

I think having something named waitWhileStale and waitUntilStale that perform the stale element checks would be useful and appropriate. I also think we could fit this into the current wait API by adding something similar to Python's staleness_of. These changes might be fine as quick temporary feature additions, but ultimately I want to create an API that unifies these things into a small set of general-purpose combinators rather than creating a proliferation of top-level wait* functions.

**Comment by kallisti-dev** [comment]
In commit 67f785a15e58aadc0f9ab98e28a741d61fddb138 I added some new functions to help with cases where you want to wait on other FailedCommand exceptions, and a function to check staleness. I think this is a step in the right direction, but there's still more to be done to make the interface easier to use.
