### ISSUE TITLE
Add the ability to extract session data from a test

### ISSUE THREAD

**Issue by beerendlauwers** [kallisti-dev/hs-webdriver#88]
A skunkworks implementation of mine, because I couldn't figure out how to extract it otherwise:

```Haskell
runSession' :: WDConfig -> WD a -> IO WDSession
runSession' conf test = do
 ref <- (newIORef undefined)
 runSession conf (dumpSessionHistoryWithIORef ref test)
 s <- readIORef ref
 return s
                                                          
dumpSessionHistoryWithIORef :: WDSessionStateControl wd => IORef WDSession -> wd a -> wd a
dumpSessionHistoryWithIORef ref = (`finally` (getSession >>= writeIORef ref))
```

Example use:
```Haskell
> runSession' remoteConfig test >>= print . wdSessHist
```

**Comment by kallisti-dev** [comment]
I don't really see this addition as being necessary to include, because it's for an impure use case that I wouldn't want to encourage people to use normally. If you want to capture session data and re-use it within multiple tests in distant code paths (perhaps threading the session state through some other Haskell framework for example) , the pure approach could could look something like this:

```hs
test1 :: WD ()
test1 = do
  someWebdriverStuff

test2 :: WD ()
test2 = do
  moreWebDriverStuff

initSession :: IO WDSession
initSession = runSession myConf getSession

runAndCapture :: WDSession -> WD a -> IO WDSession
runAndCapture s wd = runWD s (wd >> getSession)

main = do
  sess <- initSession
  sess' <- runAndCapture sess test1
  sess'' <- runAndCapture sess' test2
  doFinalizationStuff

```

A bit contrived, but if you imagine that you're working with multiple Haskell frameworks it would make more sense why you pass around

**Comment by kallisti-dev** [comment]
Closing this issue for now. I'll re-open if there's a larger consensus for this.
